---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# intuthu

<!-- badges: start -->
<!-- badges: end -->

*intuthu* veut dire "fumée" en zoulou.

Il s'agit du tableau de bord pour suivre les principaux indicateurs des SGDF.

Les données sont récupérées par FTP (bientôt SQL), traitées dans le tableau de bord et publiées.
Le tout se fait toutes les semaines par un job CRON.
L'ensemble est automatisé grâce à Github Actions.

Pour des tableaux de bord spécifiques à certaines actions, on les réalise à part, en récupérant certaines fonctions de ce dossier. La conception en package permet une reproductibilité accrue et une utilisation par des non-spécialistes.

# A FAIRE

+ récupération de données FTP/SQL
+ phase de traitement
+ tableau de bord + style
+ mise en package + décider si le tab est dans ce package ou à partnet celui-là est plus général
+ github actions
+ publication
+ définition des indicateurs cibles
+ ajout de recodage facilité des fonctions, etc...
+ faire un package pas seulement graphique, mais aussi pour faciliter les analyses, avec des référentiels, des shp de territoires, codes fonctions, etc.
+ fonction pour se connecter aux tables ?
+ ajouter des tests + un check + un code coverage auto



